/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as kiboSol from "./Kibo.sol";
export type { kiboSol };
import type * as mocks from "./mocks";
export type { mocks };
export * as factories from "./factories";
export type { IERC20 } from "./Kibo.sol/IERC20";
export { IERC20__factory } from "./factories/Kibo.sol/IERC20__factory";
export type { Kibo } from "./Kibo.sol/Kibo";
export { Kibo__factory } from "./factories/Kibo.sol/Kibo__factory";
export type { MockERC20 } from "./mocks/MockERC20";
export { MockERC20__factory } from "./factories/mocks/MockERC20__factory";
