/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface KiboInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COOLDOWN"
      | "MAX_DEPOSIT"
      | "MAX_SHIELDS"
      | "MIN_DEPOSIT"
      | "REWARD_TIER1"
      | "REWARD_TIER2"
      | "REWARD_TIER3"
      | "STREAK_THRESHOLD"
      | "cUSD"
      | "claimReward"
      | "deposit"
      | "depositors"
      | "fundPool"
      | "getLeaderboard"
      | "getUser"
      | "poolBalance"
      | "totalDepositors"
      | "users"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "PoolFunded"
      | "RewardClaimed"
      | "ShieldUsed"
      | "StreakBroken"
  ): EventFragment;

  encodeFunctionData(functionFragment: "COOLDOWN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MAX_DEPOSIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SHIELDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_DEPOSIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARD_TIER1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARD_TIER2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARD_TIER3",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STREAK_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "cUSD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLeaderboard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "poolBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalDepositors",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "users", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "COOLDOWN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DEPOSIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SHIELDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_DEPOSIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_TIER1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_TIER2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_TIER3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STREAK_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cUSD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "depositors", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fundPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLeaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDepositors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [
    user: AddressLike,
    streak: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, streak: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    streak: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolFundedEvent {
  export type InputTuple = [funder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [funder: string, amount: bigint];
  export interface OutputObject {
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    streak: BigNumberish,
    reward: BigNumberish
  ];
  export type OutputTuple = [user: string, streak: bigint, reward: bigint];
  export interface OutputObject {
    user: string;
    streak: bigint;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShieldUsedEvent {
  export type InputTuple = [
    user: AddressLike,
    streak: BigNumberish,
    shieldsLeft: BigNumberish
  ];
  export type OutputTuple = [user: string, streak: bigint, shieldsLeft: bigint];
  export interface OutputObject {
    user: string;
    streak: bigint;
    shieldsLeft: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreakBrokenEvent {
  export type InputTuple = [user: AddressLike, oldStreak: BigNumberish];
  export type OutputTuple = [user: string, oldStreak: bigint];
  export interface OutputObject {
    user: string;
    oldStreak: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Kibo extends BaseContract {
  connect(runner?: ContractRunner | null): Kibo;
  waitForDeployment(): Promise<this>;

  interface: KiboInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  MAX_DEPOSIT: TypedContractMethod<[], [bigint], "view">;

  MAX_SHIELDS: TypedContractMethod<[], [bigint], "view">;

  MIN_DEPOSIT: TypedContractMethod<[], [bigint], "view">;

  REWARD_TIER1: TypedContractMethod<[], [bigint], "view">;

  REWARD_TIER2: TypedContractMethod<[], [bigint], "view">;

  REWARD_TIER3: TypedContractMethod<[], [bigint], "view">;

  STREAK_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  cUSD: TypedContractMethod<[], [string], "view">;

  claimReward: TypedContractMethod<[], [void], "nonpayable">;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  depositors: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  fundPool: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getLeaderboard: TypedContractMethod<
    [limit: BigNumberish],
    [
      [string[], bigint[], bigint[]] & {
        addrs: string[];
        streaks: bigint[];
        totals: bigint[];
      }
    ],
    "view"
  >;

  getUser: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint, bigint] & {
        streak: bigint;
        lastDeposit: bigint;
        totalDeposited: bigint;
        longestStreak: bigint;
        canDeposit: boolean;
        lastClaimedStreak: bigint;
        shields: bigint;
      }
    ],
    "view"
  >;

  poolBalance: TypedContractMethod<[], [bigint], "view">;

  totalDepositors: TypedContractMethod<[], [bigint], "view">;

  users: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint, bigint] & {
        streak: bigint;
        longestStreak: bigint;
        lastClaimedStreak: bigint;
        lastDeposit: bigint;
        isDepositor: boolean;
        shields: bigint;
        totalDeposited: bigint;
      }
    ],
    "view"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DEPOSIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_SHIELDS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_DEPOSIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REWARD_TIER1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REWARD_TIER2"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REWARD_TIER3"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STREAK_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cUSD"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositors"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "fundPool"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getLeaderboard"
  ): TypedContractMethod<
    [limit: BigNumberish],
    [
      [string[], bigint[], bigint[]] & {
        addrs: string[];
        streaks: bigint[];
        totals: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUser"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint, bigint] & {
        streak: bigint;
        lastDeposit: bigint;
        totalDeposited: bigint;
        longestStreak: bigint;
        canDeposit: boolean;
        lastClaimedStreak: bigint;
        shields: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "poolBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalDepositors"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint, bigint] & {
        streak: bigint;
        longestStreak: bigint;
        lastClaimedStreak: bigint;
        lastDeposit: bigint;
        isDepositor: boolean;
        shields: bigint;
        totalDeposited: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "PoolFunded"
  ): TypedContractEvent<
    PoolFundedEvent.InputTuple,
    PoolFundedEvent.OutputTuple,
    PoolFundedEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "ShieldUsed"
  ): TypedContractEvent<
    ShieldUsedEvent.InputTuple,
    ShieldUsedEvent.OutputTuple,
    ShieldUsedEvent.OutputObject
  >;
  getEvent(
    key: "StreakBroken"
  ): TypedContractEvent<
    StreakBrokenEvent.InputTuple,
    StreakBrokenEvent.OutputTuple,
    StreakBrokenEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint32,uint40)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "PoolFunded(address,uint256)": TypedContractEvent<
      PoolFundedEvent.InputTuple,
      PoolFundedEvent.OutputTuple,
      PoolFundedEvent.OutputObject
    >;
    PoolFunded: TypedContractEvent<
      PoolFundedEvent.InputTuple,
      PoolFundedEvent.OutputTuple,
      PoolFundedEvent.OutputObject
    >;

    "RewardClaimed(address,uint32,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "ShieldUsed(address,uint32,uint8)": TypedContractEvent<
      ShieldUsedEvent.InputTuple,
      ShieldUsedEvent.OutputTuple,
      ShieldUsedEvent.OutputObject
    >;
    ShieldUsed: TypedContractEvent<
      ShieldUsedEvent.InputTuple,
      ShieldUsedEvent.OutputTuple,
      ShieldUsedEvent.OutputObject
    >;

    "StreakBroken(address,uint32)": TypedContractEvent<
      StreakBrokenEvent.InputTuple,
      StreakBrokenEvent.OutputTuple,
      StreakBrokenEvent.OutputObject
    >;
    StreakBroken: TypedContractEvent<
      StreakBrokenEvent.InputTuple,
      StreakBrokenEvent.OutputTuple,
      StreakBrokenEvent.OutputObject
    >;
  };
}
