/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { MockERC20, MockERC20Interface } from "../../mocks/MockERC20";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
    ],
    name: "allowance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "approve",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523461001657610398908161001c8239f35b600080fdfe60806040818152600436101561001457600080fd5b600091823560e01c908163095ea7b3146102c55750806323b872dd146101b557806340c10f191461017957806370a0823114610143578063a9059cbb146100af5763dd62ed3e1461006457600080fd5b346100ab57806003193601126100ab578060209261008061030e565b610088610329565b6001600160a01b0391821683526001865283832091168252845220549051908152f35b5080fd5b50346100ab57806003193601126100ab576100c861030e565b602435903384528360205281838520541061011057826020946101079233825281875282822085815403905560018060a01b031681522091825461033f565b90555160018152f35b825162461bcd60e51b815260206004820152600c60248201526b1a5b9cdd59999a58da595b9d60a21b6044820152606490fd5b50346100ab5760203660031901126100ab5760209181906001600160a01b0361016a61030e565b16815280845220549051908152f35b50346100ab57806003193601126100ab576001600160a01b0361019a61030e565b1682528160205281206101b0602435825461033f565b905580f35b50346100ab5760603660031901126100ab576101cf61030e565b6101d7610329565b926044359160018060a01b038091169485835260209583875284868520541061028a5780845260018752858420338552875284868520541061024d57918391869361010795528288528383208681540390556001885283832033845288528383208681540390551681528086522091825461033f565b855162461bcd60e51b8152600481018890526016602482015275696e73756666696369656e7420616c6c6f77616e636560501b6044820152606490fd5b855162461bcd60e51b8152600481018890526014602482015273696e73756666696369656e742062616c616e636560601b6044820152606490fd5b9190503461030a578060031936011261030a57916020926102e461030e565b33835260018086528284206001600160a01b039092168452908552912060243590558152f35b8280fd5b600435906001600160a01b038216820361032457565b600080fd5b602435906001600160a01b038216820361032457565b9190820180921161034c57565b634e487b7160e01b600052601160045260246000fdfea2646970667358221220993c8ccc7c11dc597ea62830e3d5e70164b041f2b2a617fa012237c2b96ef08864736f6c63430008140033";

type MockERC20ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockERC20ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockERC20__factory extends ContractFactory {
  constructor(...args: MockERC20ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockERC20 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockERC20__factory {
    return super.connect(runner) as MockERC20__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockERC20Interface {
    return new Interface(_abi) as MockERC20Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): MockERC20 {
    return new Contract(address, _abi, runner) as unknown as MockERC20;
  }
}
